version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - jsone-studios
  versioning-strategy: widen
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
