version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: '01:00'
  open-pull-requests-limit: 10
  reviewers:
  - jsone-studios
  versioning-strategy: widen
  ignore:
  - dependency-name: "@types/node"
    versions:
    - "13.x"
    - "14.x"
