name: Publish
on:
  push:
    tags: v*
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const path = require('path')
            const extractChanges = require(path.resolve("./.github/workflows/extract-changes.js"));
            const tagName = context.ref.substring(11);
            console.log(`Creating release for tag ${tagName}`);

            const changes = extractChanges(tagName);
            if (changes === null) {
              console.log("No changes found in CHANGELOG.md");
              return;
            }
            github.repos.createRelease({
              ...context.repo,
              tag_name: `v${tagName}`,
              name: tagName,
              body: changes,
            });
    

